### ISSUE TITLE
Pythonで再コーディング

### ISSUE THREAD

**Issue by pg-hobby** [pg-hobby/nettrs#9]

**Comment by LeavaTail** [comment]
作っています。

![demo](https://user-images.githubusercontent.com/33386353/94367078-2580b680-0117-11eb-870d-7240731f1ac1.gif)

**Comment by LeavaTail** [comment]
Reference

* https://github.com/LeavaTail/nettrs/commit/f11f7fbcc6ae7445511aed2e271d0df5f1bf554f
* https://github.com/LeavaTail/nettrs/commit/b2c17914b575efa149aa7791b16f2e0d8bd6d8ea
* https://github.com/LeavaTail/nettrs/commit/83c319902d31df07e376930896b9aed4ec556745

**Comment by LeavaTail** [comment]
C++のコードは別ブランチに移動させます。
